# Generated by Django 3.2.3 on 2021-06-18 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sblogs', '0009_join'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Join',
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
